apiVersion: apps/v1
kind: Deployment
metadata:
  name: redacre-backend
spec:
  selector:
    matchLabels:
      app: redacre-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redacre-backend
    spec:
      containers:
      - name: redacre-backend
        image: kurtay/backend:latest 
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: redacre-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000